/*
==========================================================
FINOVA ACCOUNTING SYSTEM
CONTROL CENTER - TAHAP 2
Database SaaS Foundation
==========================================================
TUJUAN:
- Company master
- FINOVA Super Admin
- Subscription
- Company user membership
- Hubungkan mst_users -> company secara nullable
- RLS khusus Control Center

AMAN UNTUK SISTEM EXISTING:
- Tidak mengubah AP / AR / GL / COA / report.
- mst_users.company_id dibuat NULLABLE.
==========================================================
*/

create extension if not exists pgcrypto;

create table if not exists public.finova_companies (
    id uuid primary key default gen_random_uuid(),
    company_code text not null unique,
    company_name text not null,
    legal_name text,
    email text,
    phone text,
    address text,
    max_users integer not null default 5 check (max_users > 0),
    status text not null default 'ACTIVE' check (status in ('ACTIVE','SUSPENDED','INACTIVE')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.finova_super_admins (
    id bigint generated by default as identity primary key,
    user_uid uuid not null unique references auth.users(id) on delete cascade,
    full_name text,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.finova_plans (
    id uuid primary key default gen_random_uuid(),
    plan_code text not null unique,
    plan_name text not null,
    billing_cycle text not null check (billing_cycle in ('MONTHLY','ANNUAL')),
    price numeric(18,2) not null default 0,
    max_users integer not null default 5,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.finova_subscriptions (
    id uuid primary key default gen_random_uuid(),
    company_id uuid not null references public.finova_companies(id) on delete cascade,
    plan_id uuid not null references public.finova_plans(id),
    start_date date not null,
    end_date date not null,
    amount numeric(18,2) not null default 0,
    payment_status text not null default 'UNPAID' check (payment_status in ('PAID','UNPAID','OVERDUE','CANCELLED')),
    status text not null default 'ACTIVE' check (status in ('ACTIVE','EXPIRED','CANCELLED')),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (end_date >= start_date)
);

create table if not exists public.finova_company_users (
    id uuid primary key default gen_random_uuid(),
    company_id uuid not null references public.finova_companies(id) on delete cascade,
    user_uid uuid not null references auth.users(id) on delete cascade,
    role text not null default 'STAFF' check (role in ('MANAGER','STAFF','VIEWER')),
    status text not null default 'ACTIVE' check (status in ('ACTIVE','INACTIVE')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(company_id, user_uid)
);

-- Penambahan aman untuk profile existing. Tidak NOT NULL pada Tahap 2.
alter table public.mst_users
    add column if not exists company_id uuid null references public.finova_companies(id) on delete set null;

create index if not exists idx_finova_company_users_user on public.finova_company_users(user_uid);
create index if not exists idx_finova_company_users_company on public.finova_company_users(company_id);
create index if not exists idx_finova_subscriptions_company on public.finova_subscriptions(company_id);
create index if not exists idx_finova_subscriptions_end_date on public.finova_subscriptions(end_date);
create index if not exists idx_mst_users_company_id on public.mst_users(company_id);

insert into public.finova_plans(plan_code, plan_name, billing_cycle, price, max_users)
values
    ('BUSINESS_MONTHLY', 'FINOVA Business Bulanan', 'MONTHLY', 599000, 5),
    ('BUSINESS_ANNUAL',  'FINOVA Business Tahunan', 'ANNUAL', 5990000, 5)
on conflict(plan_code) do update set
    plan_name = excluded.plan_name,
    billing_cycle = excluded.billing_cycle,
    price = excluded.price,
    max_users = excluded.max_users,
    is_active = true;

create or replace function public.finova_set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_finova_companies_updated_at on public.finova_companies;
create trigger trg_finova_companies_updated_at
before update on public.finova_companies
for each row execute function public.finova_set_updated_at();

drop trigger if exists trg_finova_subscriptions_updated_at on public.finova_subscriptions;
create trigger trg_finova_subscriptions_updated_at
before update on public.finova_subscriptions
for each row execute function public.finova_set_updated_at();

drop trigger if exists trg_finova_company_users_updated_at on public.finova_company_users;
create trigger trg_finova_company_users_updated_at
before update on public.finova_company_users
for each row execute function public.finova_set_updated_at();

-- Security definer helper supaya policy tidak recursive.
create or replace function public.is_finova_super_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.finova_super_admins a
        where a.user_uid = (select auth.uid())
          and a.is_active = true
    );
$$;

revoke all on function public.is_finova_super_admin() from public;
grant execute on function public.is_finova_super_admin() to authenticated;

-- Tenant context yang nanti dipakai pada Tahap RLS transaksi.
create or replace function public.finova_current_company_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
    select cu.company_id
    from public.finova_company_users cu
    where cu.user_uid = (select auth.uid())
      and cu.status = 'ACTIVE'
    order by cu.created_at desc
    limit 1;
$$;

revoke all on function public.finova_current_company_id() from public;
grant execute on function public.finova_current_company_id() to authenticated;

-- Super Admin dapat menghubungkan user Auth yang sudah ada ke company berdasarkan email.
create or replace function public.finova_admin_assign_user(
    p_email text,
    p_company_id uuid,
    p_role text default 'STAFF'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_uid uuid;
    v_role text;
begin
    if not public.is_finova_super_admin() then
        raise exception 'Access denied: FINOVA Super Admin required.';
    end if;

    v_role := upper(coalesce(p_role, 'STAFF'));
    if v_role not in ('MANAGER','STAFF','VIEWER') then
        raise exception 'Invalid company role.';
    end if;

    select id into v_user_uid
    from auth.users
    where lower(email) = lower(trim(p_email))
    limit 1;

    if v_user_uid is null then
        raise exception 'Auth user with email % was not found.', p_email;
    end if;

    insert into public.finova_company_users(company_id, user_uid, role, status)
    values(p_company_id, v_user_uid, v_role, 'ACTIVE')
    on conflict(company_id, user_uid)
    do update set role = excluded.role, status = 'ACTIVE', updated_at = now();

    update public.mst_users
       set company_id = p_company_id
     where user_uid = v_user_uid;

    return v_user_uid;
end;
$$;

revoke all on function public.finova_admin_assign_user(text,uuid,text) from public;
grant execute on function public.finova_admin_assign_user(text,uuid,text) to authenticated;

-- List user untuk Control Center; auth.users tidak diekspos langsung ke browser.
create or replace function public.finova_admin_list_users()
returns table(
    user_uid uuid,
    email text,
    full_name text,
    company_id uuid,
    company_name text,
    company_role text,
    membership_status text
)
language sql
stable
security definer
set search_path = ''
as $$
    select
        au.id,
        au.email::text,
        coalesce(mu.full_name, au.raw_user_meta_data ->> 'full_name', '')::text,
        cu.company_id,
        c.company_name::text,
        cu.role::text,
        cu.status::text
    from auth.users au
    left join public.mst_users mu on mu.user_uid = au.id
    left join public.finova_company_users cu on cu.user_uid = au.id and cu.status = 'ACTIVE'
    left join public.finova_companies c on c.id = cu.company_id
    where public.is_finova_super_admin()
    order by lower(coalesce(au.email,''));
$$;

revoke all on function public.finova_admin_list_users() from public;
grant execute on function public.finova_admin_list_users() to authenticated;

-- RLS Control Center.
alter table public.finova_companies enable row level security;
alter table public.finova_super_admins enable row level security;
alter table public.finova_plans enable row level security;
alter table public.finova_subscriptions enable row level security;
alter table public.finova_company_users enable row level security;

-- Pastikan tidak ada policy lama dengan nama Tahap 2.
drop policy if exists cc_admin_companies_select on public.finova_companies;
drop policy if exists cc_admin_companies_insert on public.finova_companies;
drop policy if exists cc_admin_companies_update on public.finova_companies;
drop policy if exists cc_admin_companies_delete on public.finova_companies;
create policy cc_admin_companies_select on public.finova_companies for select to authenticated using ((select public.is_finova_super_admin()));
create policy cc_admin_companies_insert on public.finova_companies for insert to authenticated with check ((select public.is_finova_super_admin()));
create policy cc_admin_companies_update on public.finova_companies for update to authenticated using ((select public.is_finova_super_admin())) with check ((select public.is_finova_super_admin()));
create policy cc_admin_companies_delete on public.finova_companies for delete to authenticated using ((select public.is_finova_super_admin()));

drop policy if exists cc_admin_plans_select on public.finova_plans;
create policy cc_admin_plans_select on public.finova_plans for select to authenticated using ((select public.is_finova_super_admin()));

drop policy if exists cc_admin_subscriptions_select on public.finova_subscriptions;
drop policy if exists cc_admin_subscriptions_insert on public.finova_subscriptions;
drop policy if exists cc_admin_subscriptions_update on public.finova_subscriptions;
drop policy if exists cc_admin_subscriptions_delete on public.finova_subscriptions;
create policy cc_admin_subscriptions_select on public.finova_subscriptions for select to authenticated using ((select public.is_finova_super_admin()));
create policy cc_admin_subscriptions_insert on public.finova_subscriptions for insert to authenticated with check ((select public.is_finova_super_admin()));
create policy cc_admin_subscriptions_update on public.finova_subscriptions for update to authenticated using ((select public.is_finova_super_admin())) with check ((select public.is_finova_super_admin()));
create policy cc_admin_subscriptions_delete on public.finova_subscriptions for delete to authenticated using ((select public.is_finova_super_admin()));

drop policy if exists cc_admin_company_users_select on public.finova_company_users;
drop policy if exists cc_admin_company_users_insert on public.finova_company_users;
drop policy if exists cc_admin_company_users_update on public.finova_company_users;
drop policy if exists cc_admin_company_users_delete on public.finova_company_users;
create policy cc_admin_company_users_select on public.finova_company_users for select to authenticated using ((select public.is_finova_super_admin()));
create policy cc_admin_company_users_insert on public.finova_company_users for insert to authenticated with check ((select public.is_finova_super_admin()));
create policy cc_admin_company_users_update on public.finova_company_users for update to authenticated using ((select public.is_finova_super_admin())) with check ((select public.is_finova_super_admin()));
create policy cc_admin_company_users_delete on public.finova_company_users for delete to authenticated using ((select public.is_finova_super_admin()));

-- Super admin hanya dapat melihat record dirinya sendiri di browser.
drop policy if exists cc_super_admin_self_select on public.finova_super_admins;
create policy cc_super_admin_self_select on public.finova_super_admins
for select to authenticated
using (user_uid = (select auth.uid()) and is_active = true);

-- Grant API privileges; RLS tetap menjadi gate utama.
grant select, insert, update, delete on public.finova_companies to authenticated;
grant select on public.finova_plans to authenticated;
grant select, insert, update, delete on public.finova_subscriptions to authenticated;
grant select, insert, update, delete on public.finova_company_users to authenticated;
grant select on public.finova_super_admins to authenticated;

-- ========================================================
-- SETELAH SCRIPT BERHASIL, JALANKAN INI DENGAN UUID OWNER:
-- ========================================================
-- insert into public.finova_super_admins(user_uid, full_name)
-- values ('UUID-AUTH-OWNER-DI-SINI', 'FINOVA Owner')
-- on conflict(user_uid) do update set is_active = true, full_name = excluded.full_name;
